PREINJ      ldx #$FF
            lda #$60
            sax $FDFC
            sax $0244
            ldy $0062
            lda #$02
            sta $EE15,Y
            lda #$48
            sax.w $0089
            sta $FE8F,Y
            lda #$03
            sax.w $008A
            sta $FE8D,Y
            lda #$34
            sax $FDD7
            lda #$FF
            sax $FE52
            lda #$03
            sax $FE4D
            lda #$81
            sax $FE48
            lda #$CC
            sax $EBA3
            sax $FD41
            lda #$05
            sax $EBA8
            sax $FD46
            lda #$08
            sax $EC26
            jmp $FD34
INJEKTOR    ldx #$FF
            lda #$D9
            sax $EBA3
            sax $FD41
            inx
            sax $EBA8
            sax $FD46
            sax $EC26
            ldx $0062
            lda #$20
            sta $FE8F,X
            lda #$01
            sta $FE8D,X
            jmp $FD34